version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --data-checksums
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

  pg-admin:
    container_name: pg-admin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 16543:80
    depends_on:
      - postgres
    networks:
      - postgres-network

volumes:
  postgres-data:


networks:
  postgres-network:
    driver: bridge
